evalPbc <- function(pbcs, mistypes = c("mnr", "mbd", "mir", "mbi"),
                    minPbcAtt = .05, maxPbcDis = .005, maxPbcMis = .07) {

  ret <- TRUE

  if(!all(c("item", "cat", "freq", "catPbc", "recodevalue") %in% names(pbcs))) {
    stop("'pbcs' should be a data.frame as generated by eatPrep::catPbc()")
  }

  if(length(setdiff(unique(pbcs$recodevalue), c(0, 1, mistypes))) > 0) {
    differing_mistypes <- setdiff(unique(pbcs$recodevalue), c(0, 1, mistypes))

    message("'catPbc' contains other values than 0, 1 and the specified mistypes:
       Other value(s): ", paste0(sort(differing_mistypes), collapse = ", "))
  }

  if(any(pbcs$freq[pbcs$recodevalue==1] == 0)) {
    message("The attractors (score 1) of the following items were chosen with a frequency of zero: ", paste0(pbcs$item[pbcs$recodevalue==1 & pbcs$freq==0], collapse=", "), ". This should not happen. Please check.\n")
    ret <- FALSE
  } else {
    message("Excellent, no attractors (score 1) were chosen with a frequency of zero.\n")
  }

   if(any(pbcs$freq[pbcs$recodevalue==0] == 0)) {
    message("The distractors (score 0) of the following items were chosen with a frequency of zero: ", paste(pbcs$item[pbcs$recodevalue==0 & pbcs$freq==0], pbcs$cat[pbcs$recodevalue==0 & pbcs$freq==0], sep="_", collapse=", "), ". This may happen, but is probably not intended.\n")
   } else {
     message("Excellent, no distractors (score 0) were chosen with a frequency of zero.\n")
   }


  ad <- ifelse(pbcs$catPbc[pbcs$recodevalue==1] < minPbcAtt | is.na(pbcs$catPbc[pbcs$recodevalue==1]), TRUE, FALSE)
    if(sum(ad) > 0) {
      message("catPbcs for attractors (score 1) of the following items are worrisome low ", paste0("(< ", format(minPbcAtt, scientific = FALSE), ")") ," or missing: ", paste(pbcs[pbcs$recodevalue==1,][ad,]$item, round(pbcs[pbcs$recodevalue==1,][ad,]$catPbc, 2), sep=":_", collapse= ", "), "\n")
      ret <- FALSE
  }

  ad <- ifelse(pbcs$catPbc[pbcs$recodevalue==0] > maxPbcDis & !is.na(pbcs$catPbc[pbcs$recodevalue==0]), TRUE, FALSE)
  if(sum(ad) > 0) {
    message("catPbcs for distractors (score 0) of the following items are unexpectedly high", paste0(" (> ", format(maxPbcDis, scientific = FALSE), ")"), ": ", paste(pbcs[pbcs$recodevalue==0,][ad,]$item, pbcs[pbcs$recodevalue==0,][ad,]$cat, round(pbcs[pbcs$recodevalue==0,][ad,]$catPbc, 2), sep="_", collapse= ", "), "\n")
    ret <- FALSE
  }

  for(mm in mistypes) {
    ad <- ifelse(pbcs$catPbc[pbcs$recodevalue==mm] > maxPbcMis & !is.na(pbcs$catPbc[pbcs$recodevalue==mm]), TRUE, FALSE)
    if(sum(ad) > 0) {
      message("catPbcs for mistype '", mm, "' of the following items are relatively high", paste0(" (> ", format(maxPbcMis, scientific = FALSE), ")"), ": ", paste(pbcs[pbcs$recodevalue==mm,][ad,]$item, pbcs[pbcs$recodevalue==mm,][ad,]$cat, round(pbcs[pbcs$recodevalue==mm,][ad,]$catPbc, 2), sep="_", collapse= ", "), "\n")
      ret <- FALSE
    }
  }

  return(ret)
}
