# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Run test coverage
        run: |
          Rscript -e 'install.packages("covr")'
          Rscript -e 'cov2 <- covr::package_coverage(type = "tests"); print(cov)'  # Debugging step
          Rscript -e 'covr::to_cobertura(cov2, file = "coverage.xml")'
          ls -lah  # Check if coverage.xml is generated

      - name: Show testthat output
        if: always()
        run: |
          ## Show testthat output if available
          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: sachseka/eatPrep
          files: coverage.xml
          fail_ci_if_error: true
